name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Saturday Group Registry
        uses: docker/login-action@v1
        with:
          registry: registry.saturdaygroup.org
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.saturdaygroup.org/game:latest
            registry.saturdaygroup.org/game:${{ github.sha }}

